name: HTML & CSS Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if specific files exist
        run: |
         # Search repo for necessary files
         if [ -f "index.html" ]; then
           echo "Files exist."
         else
           echo "Error: Files not found."
           exit 1
       
          fi
          
          echo "HTML test passed"

      - name: Display results
        run: |
          echo "HTML tests completed successfully"
